# Generated by Django 5.0.2 on 2024-02-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_category_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='element_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/image/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='default_video.mp4', upload_to='media/video/'),
        ),
    ]
