# Generated by Django 5.0.2 on 2024-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_chat2_fooditem_weighttracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat2',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
