# Generated by Django 5.0.2 on 2024-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_weighttracker_date_weighttracker_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighttracker',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
