# Generated by Django 5.0.2 on 2024-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
