# Generated by Django 5.0.2 on 2024-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_video_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
