# Generated by Django 5.0.3 on 2024-03-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_images/')),
                ('template', models.ImageField(upload_to='template_images/')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('is_queued', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
