# Generated by Django 5.0.2 on 2024-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
