# Generated by Django 5.0.2 on 2024-03-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_campaign_product_link_product_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.campaign'),
        ),
    ]
