# Generated by Django 5.0.3 on 2024-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_campaign1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign1',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign1',
            name='image',
            field=models.ImageField(upload_to='campaign_images/'),
        ),
    ]
