# Generated by Django 5.0.3 on 2024-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_campaign1_is_queued_alter_campaign1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
