# Generated by Django 5.0.3 on 2024-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_banip'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign1',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign1',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign1',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/image/'),
        ),
    ]
