# Generated by Django 5.0.3 on 2024-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_campaign1_name_campaign1_price_alter_campaign1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
