# Generated by Django 5.0.3 on 2024-04-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Media1',
        ),
    ]
