# Generated by Django 5.0.4 on 2024-04-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
