# Generated by Django 5.0.4 on 2024-04-21 10:33

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', jsonfield.fields.JSONField(default={'name': 'positions'})),
                ('pastReturns', jsonfield.fields.JSONField(default={'name': 'pastReturns'})),
                ('cash', models.IntegerField(default=1000000)),
                ('AUM', models.IntegerField(default=1000000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
